/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author alumno
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();        
        leerEntradas();
        mostrarEntrada();
    }
    
    private void leerEntradas(){
        
        agenda = new ArrayList<Entrada>(100);
        FileReader reader = null;
        BufferedReader fichero = null;
       JFileChooser fileChooser = new JFileChooser();
       int seleccion = fileChooser.showOpenDialog(null);
       
       if(seleccion == JFileChooser.APPROVE_OPTION){
       File file = fileChooser.getSelectedFile();
            try {
                 reader = new FileReader(file);
                 fichero = new BufferedReader(reader);
                String nombre, direccion, telf, telm;
                nombre = fichero.readLine(); //para esto se hace el buffered
                while(nombre != null){
                  direccion = fichero.readLine();
                  telf = fichero.readLine();
                  telm = fichero.readLine();
                agenda.add(new Entrada(nombre, direccion, Integer.parseInt(telm), Integer.parseInt(telm)));
                 
                
                nombre = fichero.readLine(); //OJO!
               
                //Volver a ponerlo 
                }
               
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
           try {
               try {
                   fichero.close();
               } catch (IOException ex) {
                   Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
               }
               reader.close();
           } catch (Exception ex) { //Poner solo exception, quitar IOException
               Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
           }
            }
           
       }
        
       // agenda.add(new Entrada ("Pepe", "Paseo Zorrilla, 125 3ºD", 983000111, 666000111));
       // agenda.add(new Entrada ("Pepa", "Plaza Zorrilla, 1 5ºD", 983000222, 666000222));
       // agenda.add(new Entrada ("Paco", "Avda. Segovia, 12", 983000333, 666000333));
       // agenda.add(new Entrada ("Ana", "C/Muro, 1", 983000444, 666000444));
       // agenda.add(new Entrada ("Carlos", "Plaza Mayor, 3", 983000555, 666000555));
       // agenda.add(new Entrada ("Marta", "C/Lopez Gomez, 12", 983000666, 666000666));
        Collections.sort(agenda);
    }
    
    private void mostrarEntrada(){
        Entrada e = agenda.get(puntero);
        txfNombre.setText(e.getNombre());
        txfDireccion.setText(e.getDireccion());
        txfFijo.setText(e.getTfnoFijo()+"");
        txfMovil.setText(e.getTfnoMovil()+"");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        txfFijo = new javax.swing.JTextField();
        txfMovil = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnPrimero = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAdd = new javax.swing.JToggleButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agenda");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tfno. Fijo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Direccion");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tfno. Movil");

        txfDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDireccionActionPerformed(evt);
            }
        });
        txfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfDireccionKeyReleased(evt);
            }
        });

        txfFijo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFijoActionPerformed(evt);
            }
        });
        txfFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfFijoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfFijoKeyTyped(evt);
            }
        });

        txfMovil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfMovilActionPerformed(evt);
            }
        });
        txfMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfMovilKeyReleased(evt);
            }
        });

        txfNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreActionPerformed(evt);
            }
        });

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/primero.png"))); // NOI18N
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/siguiente.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anterior.png"))); // NOI18N
        btnAnterior.setMaximumSize(new java.awt.Dimension(56, 56));
        btnAnterior.setMinimumSize(new java.awt.Dimension(56, 56));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ultimo.png"))); // NOI18N
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAdd.setMaximumSize(new java.awt.Dimension(56, 56));
        btnAdd.setMinimumSize(new java.awt.Dimension(56, 56));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGap(22, 22, 22))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txfMovil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                            .addComponent(txfFijo, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txfMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDireccionActionPerformed

    private void txfFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfFijoActionPerformed

    private void txfMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfMovilActionPerformed

    private void txfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:.
        
        if(puntero<agenda.size()-1){
        puntero++;
        mostrarEntrada();
        }
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        
        if(puntero>0){
        puntero--;
        mostrarEntrada();
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        // TODO add your handling code here:
        puntero =0;
        mostrarEntrada();
        
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        // TODO add your handling code here:
        puntero = agenda.size()-1;
        mostrarEntrada();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String nombrebuscar = JOptionPane.showInputDialog(this, "Teclea el nombre que desea buscar", "Buscar", INFORMATION_MESSAGE);
        Entrada eBuscar= new Entrada(nombrebuscar, null, 0,0);
        if(nombrebuscar != null){
            int indice = Collections.binarySearch(agenda, eBuscar);
            if(indice >=0){
            puntero = indice;
            mostrarEntrada();
            }else{   
 JOptionPane.showMessageDialog(this, "No está en la agenda", "Error", ERROR_MESSAGE);
 
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txfDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfDireccionKeyReleased
         // TODO add your handling code here:
      
         char digito = evt.getKeyChar(); 
         if(Character.isDigit(digito)==true){
             
            
         String sFijo = txfFijo.getText();
         int iFijo = Integer.parseInt(sFijo);
         
         if(puntero>=0){
         agenda.get(puntero).setTfnoFijo(iFijo);
         }
         agenda.get(puntero).setTfnoFijo(iFijo);
         }else{
             if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE){
             }else{
        // JOptionPane.showMessageDialog(this, "No es valido", "Error", ERROR_MESSAGE);
         int tlfnoAnterior = agenda.get(puntero).getTfnoFijo();
          txfFijo.setText(tlfnoAnterior+"");
             }
         }
         
         
    }//GEN-LAST:event_txfDireccionKeyReleased

    private void txfFijoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfFijoKeyReleased
         // TODO add your handling code here:
         String sFijo = txfFijo.getText();
        
         try{
         int iFijo = Integer.parseInt(sFijo);
         //Esto solo se hace si no salta la excepcion
         }catch(java.lang.NumberFormatException e){
          JOptionPane.showMessageDialog(this, "No es un numero valido", "Error", ERROR_MESSAGE);
          int tlfnoAnterior = agenda.get(puntero).getTfnoFijo();
          txfFijo.setText(tlfnoAnterior+"");
         }
           
    }//GEN-LAST:event_txfFijoKeyReleased

    private void txfFijoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfFijoKeyTyped
        // TODO add your handling code here:
        
          
    }//GEN-LAST:event_txfFijoKeyTyped

    private void txfMovilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfMovilKeyReleased
         // TODO add your handling code here:
         
           String sMovil = txfMovil.getText();
        
         try{
         int iFijo = Integer.parseInt(sMovil);
         //Esto solo se hace si no salta la excepcion
         }catch(java.lang.NumberFormatException e){
          JOptionPane.showMessageDialog(this, "No es un numero valido", "Error", ERROR_MESSAGE);
          int tlfnoAnterior = agenda.get(puntero).getTfnoMovil();
          txfMovil.setText(tlfnoAnterior+"");
         
         }
    }//GEN-LAST:event_txfMovilKeyReleased

    
    private void habilitarBotones(boolean b){
    btnPrimero.setEnabled(b);
    btnSiguiente.setEnabled(b);
    btnAnterior.setEnabled(b);
    btnUltimo.setEnabled(b);
    btnBuscar.setEnabled(b);
    btnBorrar.setEnabled(b);
    }
 
    private void borrarCampos(){
     txfDireccion.setText("");
         txfFijo.setText("");
         txfNombre.setText("");
         txfMovil.setText("");
    
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         // TODO add your handling code here:
         if(btnAdd.isSelected()){
         btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add2.png")));
        borrarCampos();
         habilitarBotones(false);
         txfNombre.requestFocus();
         
         }else{
         btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png")));
         String nombreAdd= txfNombre.getText();
        
         if(nombreAdd.equals("") == true){
          JOptionPane.showMessageDialog(this, "No puede estar vacio", "Error", ERROR_MESSAGE);
          mostrarEntrada();
          habilitarBotones(true);
         }else{
           
         String direccionAdd = txfDireccion.getText();
         int fijoAdd = Integer.parseInt(txfFijo.getText());
         int movilAdd = Integer.parseInt(txfMovil.getText());
         Entrada entradaAdd = new Entrada(nombreAdd, direccionAdd, fijoAdd, movilAdd);
         if(Collections.binarySearch(agenda, entradaAdd)<0){
             //Se puede añadir porque no existe 
             agenda.add(entradaAdd);
             Collections.sort(agenda);
             habilitarBotones(true);
             puntero = Collections.binarySearch(agenda, entradaAdd);
         }else{
              JOptionPane.showMessageDialog(this, "Ya existe ese nombre", "Error", ERROR_MESSAGE);
         }
            }
         }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
      
 int botonPulsado = JOptionPane.showConfirmDialog(this,
 "¿Desea borrar la entrada mostrada en pantalla?", "Borrar",
 JOptionPane.YES_NO_CANCEL_OPTION);
 switch (botonPulsado) {
 case JOptionPane.YES_OPTION:
     if(agenda.size()>0){
 agenda.remove(puntero);
 if(puntero==agenda.size()){
 puntero--;
 }
 
 if(puntero==-1){
     borrarCampos();
     habilitarBotones(false);
     btnAdd.setEnabled(true);
 }else{
 mostrarEntrada();
 }
   }
 break;
 case JOptionPane.NO_OPTION:
  JOptionPane.showMessageDialog(this, "La entrada no ha sido borrada", "Aviso", JOptionPane.INFORMATION_MESSAGE);
 
 break;
 case JOptionPane.CANCEL_OPTION:
   JOptionPane.showMessageDialog(this, "La operacion ha sido cancelada", "Aviso", JOptionPane.INFORMATION_MESSAGE);
 break;
 default:
       JOptionPane.showMessageDialog(this, "La ventana ha sido cerrada", "Aviso", JOptionPane.INFORMATION_MESSAGE);

 break;
 }
 
        
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdd;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfFijo;
    private javax.swing.JTextField txfMovil;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables

private ArrayList<Entrada> agenda;
private int puntero =0; //Indicar la posicion en la que se esta 
}
